"$schema" = 'https://starship.rs/config-schema.json'

# Configures the format of the prompt.
format = """
[ÓÇ∂](color_red0)\
$os\
$username\
[ÓÇ¥](bg:color_orange fg:color_red0)\
$directory\
[ÓÇ¥](fg:color_orange bg:color_yellow)\
$git_branch\
$git_status\
[ÓÇ¥](fg:color_yellow bg:color_green)\
$c\
$dotnet\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$elixir\
$elm\
$gradle\
$julia\
$nim\
$scala\
[ÓÇ¥](fg:color_green bg:color_cyan)\
$docker_context\
[ÓÇ¥ ](color_cyan)\
$fill\
([ ÓÇ∂](mono4)\
$time\
$battery\
[ÓÇ¥](mono4))\
$line_break$character"""

# Sets the palette to "one_dark".
palette = 'one_dark'

# Sets the colors of the "one_dark" palette.
[palettes.one_dark]
mono0 = '#d7dae0' # terminal white, from the One Dark Pro VSCode theme.
mono1 = '#abb2bf' # syntax_fg.
mono2 = '#828997'
mono3 = '#5c6370'
mono4 = '#3f4451' # terminal black, from the One Dark Pro VSCode theme.
color_red0 = '#e06c75'
color_red1 = '#be5046'
color_green = '#98c379'
color_yellow = '#e5c07b'
color_blue = '#61afef'
color_purple = '#c678dd'
color_cyan = '#56b6c2'
color_orange = '#d19a66'
syntax_fg = '#abb2bf'
syntax_bg = '#282c34'
color_bg2 = '#665c54'
syntax_gutter = '#647382'
syntax_accent = '#528cff'

# Module that displays the current OS.
[os]
disabled = false # Disabled by default
style = "bg:color_red0 fg:syntax_bg"
format = '[ $symbol ]($style)'

# Sets custom symbols for each OS.
[os.symbols]
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Û∞Ä≤"
Arch = "ÔåÉ"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
EndeavourOS = "Ôå¢"
Fedora = "Û∞£õ"
FreeBSD = "Û∞£†"
Gentoo = "Û∞£®"
Illumos = "Ôå¶"
Linux = "Û∞åΩ"
Macos = "Û∞Äµ"
Manjaro = "Û±òä"
Mint = "Û∞£≠"
NixOS = "Û±ÑÖ"
OpenBSD = "Ôå®"
openSUSE = "Ôåî"
Pop = "Ôå™"
Raspbian = "Ôåï"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Redox = "R"
Solus = "Ôå≠"
SUSE = "Ôåî"
Ubuntu = "Û∞ïà"
Unknown = "ÔÅô"
Windows = "Û∞ç≤"

# Module that displays the current username.
[username]
show_always = true
style_user = "bold bg:color_red0 fg:syntax_bg"
style_root = "bold italic bg:color_red0 fg:syntax_bg"
format = '[ $user ]($style)'

# Module that displays the current directory.
[directory]
style = "italic fg:syntax_bg bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

# Sets the custom symbols for directories.
[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "

# Module that displays the current git branch.
[git_branch]
symbol = "Ôêò"
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:syntax_bg bg:color_yellow)]($style)'

# Module that displays the current git status.
[git_status]
style = "bg:color_yellow"
conflicted = 'üè≥'
up_to_date = ''
untracked = 'Ôî© '
ahead = '‚á°${count}'
diverged = '‚áï‚á°${ahead_count}‚á£${behind_count}'
behind = '‚á£${count}'
stashed = 'Ô£ñ '
modified = 'ÔÅÑ '
staged = '++\($count\)'
renamed = 'Ô™∂ '
deleted = 'ÔÄî '
format = '[[($all_status$ahead_behind )](fg:syntax_bg bg:color_yellow)]($style)'

# Language specific modules
[nodejs]
symbol = "Óúò"
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[c]
symbol = "Óòû "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[dotnet]
symbol = "Û∞™Æ"
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[golang]
symbol = "Óòß"
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[php]
symbol = "Óòà "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[java]
symbol = "Óâñ "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[kotlin]
symbol = "Óò¥ "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[haskell]
symbol = "Óòü "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[python]
symbol = "ÓòÜ "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_green)]($style)'

[elixir]
symbol = "Óâµ "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[elm]
symbol = "Óò¨ "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[gradle]
symbol = "Óô† "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[julia]
symbol = "Óò§ "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[nim]
symbol = "Û∞Ü• "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

[scala]
symbol = "Óú∑ "
style = "bg:color_green"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_green)]($style)'

# Module that displays the docker context.
[docker_context]
symbol = "Ôåà "
style = "bg:mono3"
format = '[[ $symbol( $context) ](fg:syntax_fg bg:mono3)]($style)'

# Module that fills the space between the left and right segments.
[fill]
symbol = " "

# Module that displays the time.
[time]
disabled = false # Disabled by default
use_12hr = true # Disable for 24h format without seconds
style = "bg:mono4"
format = '[[ Û∞•î $time ](fg:syntax_fg bg:mono4)]($style)'

# Module that displays the battery level and status.
[battery]
format = '[$symbol $percentage ]($style)'

# Battery symbols and colors for each threshold.
[[battery.display]]
threshold = 10
style = "bold bg:mono4 fg:color_red1"
discharging_symbol = "Û∞Å∫"
charging_symbol = "Û∞¢ú"

[[battery.display]]
threshold = 20
style = "bold bg:mono4 fg:color_red0"
discharging_symbol = "Û∞Åª"
charging_symbol = "Û∞ÇÜ"

[[battery.display]]
threshold = 30
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "Û∞Åº"
charging_symbol = "Û∞Çá"

[[battery.display]]
threshold = 40
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "Û∞ÅΩ"
charging_symbol = "Û∞Çà"

[[battery.display]]
threshold = 50
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "Û∞Åæ"
charging_symbol = "Û∞¢ù"

[[battery.display]]
threshold = 60
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "Û∞Åø"
charging_symbol = "Û∞Çâ"

[[battery.display]]
threshold = 70
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "Û∞ÇÄ"
charging_symbol = "Û∞¢û"

[[battery.display]]
threshold = 80
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "Û∞ÇÅ"
charging_symbol = "Û∞Çä"

[[battery.display]]
threshold = 90
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "Û∞ÇÇ"
charging_symbol = "Û∞Çã"

[[battery.display]]
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "Û∞Åπ"
charging_symbol = "Û∞ÇÖ"
threshold = 100

# New line character
[character]
success_symbol = '[Û∞ÖÇ](bold fg:syntax_accent)'
error_symbol = '[Ôëß](bold fg:color_red1)'
vimcmd_symbol = '[Û∞ÖÅ](bold fg:syntax_accent)'
vimcmd_replace_one_symbol = '[Û∞ÖÅ](bold fg:color_purple)'
vimcmd_replace_symbol = '[Û∞ÖÅ](bold fg:color_purple)'
vimcmd_visual_symbol = '[Û∞ÖÅ](bold fg:color_yellow)'